#!/bin/bash
# Creates ssh-connection for git

newdir=.ssh

if [ -d ~/$newdir ]; then
    echo "Directory $newdir exist"
else 
    echo "Create $newdir"
    mkdir ~/$newdir
    cd ~/$newdir
fi

ssh-keygen -t rsa -b 4096 -C "fan.42@mail.ru" -f ~/$newdir/git_rsa
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/git_rsa
echo "<=== KEY FOR GitHub ===>"
cat git_rsa.pub

