#!/bin/bash
# Creates ssh-connection for git
newdir=.ssh

if [ -d ~/$newdir ]; then
    echo "DIRECTORY $newdir EXISTS"
else 
    echo "CREATED $newdir"
    mkdir ~/$newdir
    cd ~/$newdir
fi

echo "MAKE CONFIGS FOR GIT"
git config --global user.email fan.42@mail.ru
git config --global user.name fanishe

if [ -f ~/$newdir/git_rsa ]; then
    echo "=== GIT EXISTS ==="
else 
    ssh-keygen -t rsa -b 4096 -C "fan.42@mail.ru" -f ~/$newdir/git_rsa
fi

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/git_rsa

echo "<=== KEY FOR GitHub ===>"
cat ~/$newdir/git_rsa.pub

