# ====== My Aliases ======
alias c='clear'
alias q='exit'
alias upd='sudo apt-get update'
alias upg='sudo apt-get upgrade'
alias updg='sudo apt-get update && sudo apt-get upgrade -y'
alias adal='sudo vim ~/.bashrc'
alias refal='source ~/.bashrc'
alias fddns='ssh -p 40408 fantomas@fantomas.ddns.net'
alias myflask='cd /mnt/c/Users/PC/Documents/GitHub/flask/microblog/'
alias pip='pip3'
alias py='python3'
alias venv='source /mnt/c/Users/PC/Documents/GitHub/flask/microblog/venv/bin    /activate'
alias out='deactivate'
alias bot='cd /mnt/c/Users/PC/Documents/GitHub/bot'
alias desctop='cd /mnt/c/Users/PC/Desktop'
alias ls='ls -a'
alias aws='ssh -i ~/.ssh/"aws_webserver_frankfurt.pem" ubuntu@ec2-3-120-204-255.eu-central-1.compute.amazonaws.com'
