#!/bin/bash
# Creates ssh-connection for git

# Colors for console
# https://m.habr.com/ru/post/119436/

newdir=.ssh
RED='\033[0;31m'         #  ${RED}
GREEN='\033[0;32m'      #  ${GREEN}
NORMAL='\033[0m'      #  ${NORMAL}
YELLOW='\033[0;33m'     #  ${YELLOW}

if [ -d ~/$newdir ]; then
    echo -e "${RED} DIRECTORY $newdir EXISTS${NORMAL}"
else 
    echo "${GREEN}CREATED $newdir${NORMAL}"
    mkdir ~/$newdir
    cd ~/$newdir
fi

echo -e "${YELLOW}MAKE CONFIGS FOR GIT${NORMAL}"
git config --global user.email fan.42@mail.ru
git config --global user.name fanishe
cat ~/.gitconfig

if [ -f ~/$newdir/git_rsa ]; then
    echo -e "${RED}=== git_rsa EXISTS ===${NORMAL}"
else 
    ssh-keygen -t rsa -b 4096 -C "fan.42@mail.ru" -f ~/$newdir/git_rsa
fi

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/git_rsa

echo -e "${YELLOW}<=== KEY FOR GitHub ===>${NORMAL}"
cat ~/$newdir/git_rsa.pub

